name: Build OpenWrt Firmware

on:
  workflow_dispatch:
    inputs:
      imagebuilder:
        description: "OpenWrt ImageBuilder Tag"
        required: true
        default: "x86-64-25.12.3"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker Version
        run: docker version

      - name: Pull ImageBuilder
        run: |
          docker pull openwrt/imagebuilder:${{ github.event.inputs.imagebuilder }}

      - name: Build Firmware
        run: |
          chmod +x build.sh

          docker rm -f ob || true
          docker create --name ob openwrt/imagebuilder:${{ github.event.inputs.imagebuilder }}

          docker cp build.sh ob:/builder/build.sh
          docker cp files ob:/builder/files || true

          docker start -a ob

          mkdir -p bin
          docker cp ob:/builder/bin/targets ./bin/targets

          docker rm ob

      - name: Show Output
        run: |
          find bin -type f

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: bin/targets/**/*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.imagebuilder }}
          name: OpenWrt-${{ github.event.inputs.imagebuilder }}
          generate_release_notes: true
          files: bin/targets/**/*